bg_cinema:
    resource: "@BGCinemaBundle/Resources/config/routing.yml"

bg_cinema_paramconverter:
    path: /test/{json}
    defaults:
        _controller: "BGCinemaBundle:Advert:ParamConverter"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
