parameters:


services:
    admin.category:
        class: BG\CinemaBundle\Admin\CategoryAdmin
        arguments: [~, BG\CinemaBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
        public: true
