bg_platform_home:
    path:      /{page}
    defaults:
        _controller: BGPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

bg_platform_view:
    path:      /advert/{advert_id}
    defaults:
        _controller: BGPlatformBundle:Advert:view
    requirements:
        id: \d+

bg_platform_add:
    path:      /add
    defaults:
        _controller: BGPlatformBundle:Advert:add

bg_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: BGPlatformBundle:Advert:edit
    requirements:
        id: \d+

bg_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: BGPlatformBundle:Advert:delete
    requirements:
        id: \d+

bg_platform_purge:
    path:     /purge/{days}
    defaults:
        _controller: BGPlatformBundle:Advert:purge
    requirements:
        days: \d+
