services:
  bg_platform.antispam:
      class: BG\PlatformBundle\Antispam\BGAntispam
      arguments:
          - "@mailer"
          - %locale%
          - 50

  bg_platform.email.application_mailer:
      class: BG\PlatformBundle\Email\ApplicationMailer
      arguments:
          - "@mailer"

  bg_platform.doctrine_listener.application_creation:
    class: BG\PlatformBundle\DoctrineListener\ApplicationCreationListener
    arguments:
      - "@bg_platform.email.application_mailer"
    tags:
      - { name: doctrine.event_listener, event: postPersist }

  bg_platform.purger.advert:
    class: BG\PlatformBundle\Purger\AdvertPurger
    arguments:
      - "@doctrine.orm.entity_manager"

  bg_platform.validator.antiflood:
    class: BG\PlatformBundle\Validator\AntifloodValidator
    arguments: ["@request_stack", "@doctrine.orm.entity_manager"] # les données qu'on injecte au service : la requete et l'EntityManager
    tags:
      - { name: validator.constraint_validator, alias: bg_platform_antiflood } # C'est avec cet alias qu'on retrouvera le service

  bg_platform.twig.antispam_extension:
    class: BG\PlatformBundle\Twig\AntispamExtension
    arguments:
      - "@bg_platform.antispam"
    tags:
      - { name: twig.extension }

  bg_platform.form.ckeditor:
    class: BG\PlatformBundle\Form\CkeditorType
    tags:
      - { name: form.type, alias: ckeditor }

  bg_platform.beta.html_adder:
    class: BG\PlatformBundle\Beta\BetaHTMLAdder

  bg_platform.beta.listener:
    class: BG\PlatformBundle\Beta\BetaListener
    arguments:
      - "@bg_platform.beta.html_adder"
      - "2018-02-15"
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: processBeta }

    bg_platform.paramconverter.json:
      class:  BG\PlatformBundle\ParamConverter\JsonParamConverter
      tags:
        - { name: request.param_converter }
