bg_cinema_home:
    path:      /
    defaults:
        _controller: BGCinemaBundle:Film:index
        page : 1

bg_cinema_view:
    path:      /film/{film_id}
    defaults:
        _controller: BGCinemaBundle:Film:view
    requirements:
        id: \d+

bg_cinema_add:
    path:      /add
    defaults:
        _controller: BGCinemaBundle:Film:add

bg_cinema_edit:
    path:      /edit/{id}
    defaults:
        _controller: BGCinemaBundle:Film:edit
    requirements:
        id: \d+

bg_cinema_delete:
    path:      /delete/{id}
    defaults:
        _controller: BGCinemaBundle:Film:delete
    requirements:
        id: \d+

bg_cinema_purge:
    path:     /purge/{days}
    defaults:
        _controller: BGCinemaBundle:Film:purge
    requirements:
        days: \d+

bg_cinema_debats:
    path: /cine-debat
    defaults:
        _controller: BGCinemaBundle:Film:debats

bg_cinema_americain:
    path: /cycle-americain
    defaults:
        _controller: BGCinemaBundle:Film:americain

bg_cinema_evenements:
    path: /autres-evenements
    defaults:
        _controller: BGCinemaBundle:Film:evenements

bg_cinema_jeunepublic:
    path: /jeune-public
    defaults:
        _controller: BGCinemaBundle:Film:jeunepublic

bg_cinema_apropos:
    path: /à-propos
    defaults:
        _controller: BGCinemaBundle:Film:apropos

bg_cinema_pratique:
    path: /pratique
    defaults:
        _controller: BGCinemaBundle:Film:pratique
